import type { Metadata } from 'next'
import './globals.css'
import { archivo, grotesk } from './fonts/fonts'
import Header from './components/Header'
import Footer from './components/Footer'

export const metadata: Metadata = {
  title: 'Loki - A série',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${grotesk.variable} ${archivo.variable}`}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
